---
label: Base
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: boolean
  name: toc
  label: toc
- type: list
  name: images
  label: images
- type: list
  name: tags
  label: tags
- type: list
  name: categories
  label: categories
- type: list
  name: series
  label: series
