---
label: Base
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: boolean
  name: toc
  label: toc
- type: list
  name: images
  label: images
- type: list
  name: tags
  label: tags
- type: list
  name: categories
  label: categories
- type: list
  name: series
  label: series
pages:
- content/en/posts/coding/javascript/Vanila Javascript/lexical-structure.md
- content/vi/posts/Operating System/file-management.md
- content/vi/posts/Operating System/windows-8-1.md
